# tour_route.py
"""
도리 투어 전체 동선 정의
언어별 이름 포함, 마지막 스팟(경회루)은 사진 촬영 지점
"""

TOUR_ROUTE = [
    {
        "spot_code": "gwanghwamun",
        "order": 1,
        "is_photo_spot": False,
        "name_ko": "광화문",
        "name_en": "Gwanghwamun Gate",
        "name_ja": "光化門",
        "name_zh": "光化门",
        "name_fr": "Gwanghwamun",
        "name_es": "Gwanghwamun",
        "name_vi": "Gwanghwamun",
        "name_th": "กวางฮวามุน",
    },
    {
        "spot_code": "heungnyemun",
        "order": 2,
        "is_photo_spot": False,
        "name_ko": "흥례문",
        "name_en": "Heungnyemun Gate",
        "name_ja": "興礼門",
        "name_zh": "兴礼门",
        "name_fr": "Heungnyemun",
        "name_es": "Heungnyemun",
        "name_vi": "Heungnyemun",
        "name_th": "ฮึงนเยมุน",
    },
    {
        "spot_code": "geunjeongmun",
        "order": 3,
        "is_photo_spot": False,
        "name_ko": "근정문",
        "name_en": "Geunjeongmun Gate",
        "name_ja": "勤政門",
        "name_zh": "勤政门",
        "name_fr": "Geunjeongmun",
        "name_es": "Geunjeongmun",
        "name_vi": "Geunjeongmun",
        "name_th": "กึนจองมุน",
    },
    {
        "spot_code": "geunjeongjeon",
        "order": 4,
        "is_photo_spot": False,
        "name_ko": "근정전",
        "name_en": "Geunjeongjeon Hall",
        "name_ja": "勤政殿",
        "name_zh": "勤政殿",
        "name_fr": "Geunjeongjeon",
        "name_es": "Geunjeongjeon",
        "name_vi": "Geunjeongjeon",
        "name_th": "กึนจองจอน",
    },
    {
        "spot_code": "sujeongjeon",
        "order": 5,
        "is_photo_spot": False,
        "name_ko": "수정전",
        "name_en": "Sujeongjeon Hall",
        "name_ja": "修政殿",
        "name_zh": "修政殿",
        "name_fr": "Sujeongjeon",
        "name_es": "Sujeongjeon",
        "name_vi": "Sujeongjeon",
        "name_th": "ซูจองจอน",
    },
    {
        "spot_code": "gyeonghoeru",
        "order": 6,
        "is_photo_spot": True,
        "name_ko": "경회루",
        "name_en": "Gyeonghoeru Pavilion",
        "name_ja": "慶会楼",
        "name_zh": "庆会楼",
        "name_fr": "Gyeonghoeru",
        "name_es": "Gyeonghoeru",
        "name_vi": "Gyeonghoeru",
        "name_th": "คยองฮเวรู",
    },
]
